AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SqsApiGatewayIntegration

  Sample SAM Template for SqsApiGatewayIntegration
Globals:
  Function:
    Timeout: 3

Resources:
  SQSProcessor:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      Events:
        PollQueue:
          Type: SQS
          Properties:
            Queue: !GetAtt MessageQueue.Arn
            FunctionResponseTypes: ReportBatchItemFailures

  MessageQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ExerciseQueue

  SendMessageApi:
    Type: AWS:Serverless::Api
    Properties:
      StageName: dev
      DefinitionBody:
        swagger: '2.0'
        paths:
          /send:
            post:
              responses:
                '200':
                  description: OK
                '400':
                  description: BAD REQUEST
                '500':
                  description: INTERNAL ERROR
              x-amazon-apigateway-integration:
                type: aws
                uri: !Sub arn:aws:apigateway:${AWS::Region}:sqs:action/SendMessage

  SendMessageApiRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SendMessagePermissionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource: !GetAtt MessageQueue.Arn